name: Items
author: Wertik1206
version: ${project.version}
api-version: 1.13
main: space.devport.wertik.items.ItemsPlugin
softdepend: [PlaceholderAPI]
commands:
  items:
    aliases: [i, item]
    description: Main command for item manipulation.
  attributes:
    aliases: [att, attribute]
    description: Main command for attribute manipulation.
  detail:
    description: View item details.
  setname:
    description: Set items display name.
  itemextra:
    description: Manage extra item properties.
  lore:
    description: Manage lore.
  enchants:
    description: Manage enchantments.
  flags:
    description: Manage flags.
permissions:
  items.control:
    description: Allows commands