name: Items
author: Wertik1206
version: ${project.version}
main: space.devport.wertik.items.ItemsPlugin
commands:
  items:
    aliases: [i]
    description: Main command for handling items.
  attribute:
    aliases: [att]
    description: Main command for attribute manipulation.
  detail:
    description: View item details.
  setname:
    description: Set items display name.
  addench:
    description: Add enchant to your item.
  enchs:
    description: Display enchants on your item
  remench:
    description: Remove enchant from your item.
  flags:
    description: View item flags.
  addflag:
    description: Add an ItemFlag to your item.
  remflag:
    description: Remove an item flag from your item.
  lore:
    description: View item lore.
  addlore:
    description: Add lore line to your item.
  remlore:
    description: Remove lore line from your item.
permissions:
  items.control:
    description: Allows commands